config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  get 'likes/create'

  resources :venues, only: [:show, :new, :create] do
    resources :check_ins, only: [:create]
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  root 'welcome#index'
  get "offer" => "venues#offer"

  get "like/:venue_id" => "likes#create", as: "likes"

  resources :users do
    member do
      post :follow
      post :unfollow
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq_ui'
end

app/views/shared/_custom_scripts.html.erb
<script>
  window.dispatcher = window.dispatcher || new WebSocketRails(window.document.location.host + "/websocket");

  var channel = dispatcher.subscribe('follow');

  channel.bind('success', function(user) {
    var followed_id = user.id;
    var current_user_id = <%= current_user.try(:id) %>;

    if(followed_id === current_user_id) {
      $( '<div class="alert alert-success" role="alert">You are followed!! YAY</div>' ).insertAfter( ".header" );
    }
  });
</script>

app/views/shared/_header.html.erb
<div class="header clearfix">
  <nav>
    <ul class="nav nav-pills pull-right">
      <% if current_user %>
          <li>
            <%= form_tag search_venues_path do  %>
              <%= text_field_tag :q %>

              <%= button_tag "Send" %>
            <% end %>
          </li>
        <li role="presentation"><%= link_to "Find Me!", offer_path, remote: true %></li>
        <li role="presentation" class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %><span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li role="presentation">
              <%= link_to "Profile", user_path(current_user) %>
            </li>
            <li role="presentation"><%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
            </li>
          </ul>
      <% else %>
        <li role="presentation"><%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %></li>
        <li role="presentation"><%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %></li>
        <li role="presentation"><%= link_to "Sign in with Google+", user_omniauth_authorize_path(:google_oauth2) %></li>
      <% end %>
    </ul>
  </nav>
  <h3 class="text-muted">
    <%= link_to 'Railsquare', root_path %>
  </h3>
</div>