config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  get 'likes/create'

  resources :venues, only: [:show, :new, :create] do
    resources :check_ins, only: [:create]
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  root 'welcome#index'
  get "offer" => "venues#offer"

  get "like/:venue_id" => "likes#create", as: "likes"

  resources :users do
    member do
      post :follow
      post :unfollow
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq_ui'
end

app/models/venue.rb
# == Schema Information
#
# Table name: venues
#
#  id          :integer          not null, primary key
#  name        :string
#  address     :text
#  category_id :integer
#  latitude    :float
#  longitude   :float
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Venue < ActiveRecord::Base
	belongs_to :category
	has_many :check_ins
	has_many :likes
	has_many :users, through: :likes

	geocoded_by :address
	after_validation :geocode

	validates :name, presence: true

	include PgSearch
	pg_search_scope :search, :against => [:name, :address],
									:using => {
											:tsearch => {:prefix => true}
									}
	pg_search_scope :search_by_name, :against => [:name]
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def new
    @venue = Venue.new
  end

  def create
    @venue = Venue.new(venue_params)

    if @venue.save
      redirect_to @venue, notice: 'Venue created successfully'
    else
      render 'new', alert: @venue.errors
    end
  end

  def show
    @venue = Venue.find(params[:id])
  end

  def offer
    latitude = request.location.latitude
    longitude = request.location.longitude
    #Venue.near([latitude, longitude], 1000, units: :km)
    @venues = Venue.near([39.998, 32.8799], 10, units: :km)
  end

  def search
    @venues = Venue.search(params[:q])
  end

  private
    def venue_params
      params.require(:venue).permit(:name, :address, :category_id)
    end
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/_venues.html.erb
<% @venues.each do |venue| %>
	<div class="col-md-6 col-offset-3">
    <h4><%= link_to venue.name, venue_path(venue) %></h4>
    <p><%= venue.address %></p>
  </div>
<% end %>

app/views/venues/new.html.erb
<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <h1>New Venue</h1>
    <% @venue.errors.full_messages.each do |message| %>
      <div class="alert alert-danger" role="alert">
        <span class="sr-only">Error:</span>
        <%= message %>
      </div>
    <% end %>
    <%= form_for @venue do |f| %>
      <div class='form-group'>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class='form-group'>
        <%= f.text_area :address, class: 'form-control' %>
      </div>
      <div class='form-group'>
        <%= f.select :category_id, Category.all.map{|c| [c.name, c.id]}, {}, class: 'form-control' %>
      </div>
      <%= f.submit class: 'btn btn-success' %>
    <% end %>

  </div>
</div>

<%= javascript_include "search.js" %>

app/views/venues/offer.js.erb
$(".venues").html("<%= j raw render('venues') %>")

app/views/venues/search.html.erb
<div class="row">
  <div class="col-md-12">
    <%= render 'venues/venues' %>
  </div>
</div>

app/views/venues/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h2><%= @venue.name %></h2>

  </div>
</div>

<div id='map' style="height: 400px;">

</div>

<div class="row venue">
  <div class="col-md-12">
    <div class="check-button">
      <% if current_user.try(:checked_venue?, @venue) %>
        <button type="button" class="btn btn-primary btn-lg">
          <span class="glyphicon glyphicon-check" aria-hidden="true"></span>
          Checked
          <span class="badge"><%= @venue.check_ins.size %></span>
        </button>
      <% else  %>
        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
          <span class="glyphicon glyphicon-check" aria-hidden="true"></span>
          Check-In
          <span class="badge"><%= @venue.check_ins.size %></span>
        </button>
      <% end %>
    </div>
    <%= link_to likes_path(@venue.id), remote: true, class: "btn btn-warning btn-lg btn-like" do %>
      <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
        <%= current_user.liked_venue?(@venue) ? "Liked" : "Like venue" %>
      <span class="badge"><%= @venue.likes.size %></span>
    <% end %>
  </div>
</div>

<div class="row marketing venues">
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Check-In</h4>
      </div>

      <%= form_for CheckIn.new, url: venue_check_ins_path(@venue), remote: true do |f| %>
        <div class="modal-body">
          <%= f.file_field :image %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<h2>Check-Ins</h2>
<div class='row'>
  <div class='col-md-12'>
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <% @venue.check_ins.each_with_index do |check_in, index| %>
          <div class="item <%= index == 0 ? 'active' : '' %>">
            <div class='carousel-image-container'>
              <%= image_tag check_in.image %>
            </div>
          </div>
        <% end %>
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
</div>

<script>
function initMap() {
  var myLatLng = {lat: <%= @venue.latitude %>, lng: <%= @venue.longitude %>};

  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 14,
    center: myLatLng
  });

  var marker = new google.maps.Marker({
    position: myLatLng,
    map: map
  });
}
</script>
<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC6_EYrj_hd3d7f5vTF2leqc7wLxEcdVHw&signed_in=true&callback=initMap"></script>